import { DEFAULT_LOGO_DATA_URL } from '../defaultLogoDataUrl'
import type { SignatureFormState } from '../types/signatureForm'

export const createDefaultFormState = (): SignatureFormState => ({
  signatureLanguage: 'he',
  fullName: '',
  jobTitle: '',
  company: '',
  phone: '',
  email: '',
  website: '',
  facebookUrl: 'https://www.facebook.com/SBAIsrael',
  facebookIconUrl: '',
  instagramUrl: 'https://www.instagram.com/sba.israel?igsh=MXUyYjI5a3UxMmZidg==',
  instagramIconUrl: '',
  linkedinUrl: 'https://www.linkedin.com/in/misradacalcala/',
  linkedinIconUrl: '',
  xUrl: 'https://x.com/misrad_calcala',
  xIconUrl: '',
  youtubeUrl: 'https://www.youtube.com/user/SBAIsrael',
  youtubeIconUrl: '',
  logoUrl: DEFAULT_LOGO_DATA_URL,
  bannerUrl: '',
  bannerLink: '',
  linkImages: [{ id: 'initial-link-image', imageUrl: '', href: '', alt: '' }],
  fontFamily: "'Rubik', Arial, Helvetica, sans-serif",
  nameFontSize: 28,
  titleFontSize: 19,
  bodyFontSize: 12,
  lineSpacing: 1.1,
  signatureWidth: 400,
  signatureHeight: 200,
  textColumnWidth: 252,
  logoMaxWidth: 122,
  textAlign: 'right',
  nameTitleAlign: 'right',
  emailAlign: 'right',
  logoAlign: 'right',
  verticalAlign: 'top',
  textOffsetX: 0,
  textOffsetY: 0,
  logoOffsetX: 10,
  logoOffsetY: 6,
  dividerThickness: 2,
  socialIconGap: 5,
  accentColor: '#88236f',
  textColor: '#4c4c4e',
  secondaryTextColor: '#4d4c4f',
  dividerColor: '#30bbed',
  linkColor: '#4c4c4e',
  backgroundColor: '#ffffff'
})
