import { DEFAULT_LOGO_DATA_URL } from '../defaultLogoDataUrl'
import { SBA_BRAND_PRESETS } from '../brandPresets'
import { DEFAULT_SOCIAL_ICON_VARIANT } from './socialIconCatalog'
import type { SignatureFormState } from '../types/signatureForm'

const DEFAULT_BRAND_PRESET = SBA_BRAND_PRESETS[0].values

export const createDefaultFormState = (): SignatureFormState => ({
  signatureLanguage: 'he',
  fullName: '',
  jobTitle: '',
  company: '',
  phone: '',
  email: '',
  website: '',
  facebookUrl: 'https://www.facebook.com/SBAIsrael',
  facebookIconUrl: '',
  facebookIconVariant: DEFAULT_SOCIAL_ICON_VARIANT.Facebook,
  instagramUrl: 'https://www.instagram.com/sba.israel?igsh=MXUyYjI5a3UxMmZidg==',
  instagramIconUrl: '',
  instagramIconVariant: DEFAULT_SOCIAL_ICON_VARIANT.Instagram,
  linkedinUrl: 'https://www.linkedin.com/in/misradacalcala/',
  linkedinIconUrl: '',
  linkedinIconVariant: DEFAULT_SOCIAL_ICON_VARIANT.LinkedIn,
  xUrl: 'https://x.com/misrad_calcala',
  xIconUrl: '',
  xIconVariant: DEFAULT_SOCIAL_ICON_VARIANT.X,
  youtubeUrl: 'https://www.youtube.com/user/SBAIsrael',
  youtubeIconUrl: '',
  youtubeIconVariant: DEFAULT_SOCIAL_ICON_VARIANT.YouTube,
  logoUrl: DEFAULT_LOGO_DATA_URL,
  bannerUrl: '',
  bannerLink: '',
  linkImages: [{ id: 'initial-link-image', imageUrl: '', href: '', alt: '' }],
  fontFamily: DEFAULT_BRAND_PRESET.fontFamily,
  nameFontWeight: 700,
  titleFontWeight: 600,
  bodyFontWeight: 400,
  nameFontSize: 28,
  titleFontSize: 19,
  bodyFontSize: 12,
  lineSpacing: 1.1,
  signatureWidth: 400,
  signatureHeight: 200,
  textColumnWidth: 252,
  logoMaxWidth: 122,
  textAlign: 'right',
  nameTitleAlign: 'right',
  emailAlign: 'right',
  logoAlign: 'right',
  logoSide: 'right',
  verticalAlign: 'top',
  textOffsetX: 0,
  textOffsetY: 0,
  logoOffsetX: 10,
  logoOffsetY: 6,
  dividerThickness: 2,
  socialIconGap: 5,
  accentColor: DEFAULT_BRAND_PRESET.accentColor,
  textColor: DEFAULT_BRAND_PRESET.textColor,
  secondaryTextColor: DEFAULT_BRAND_PRESET.secondaryTextColor,
  dividerColor: DEFAULT_BRAND_PRESET.dividerColor,
  linkColor: DEFAULT_BRAND_PRESET.linkColor,
  backgroundColor: DEFAULT_BRAND_PRESET.backgroundColor
})
